# Generated by Django 4.2.14 on 2024-07-15 21:33

import core.recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_recipe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(blank=True, null=True, upload_to=core.recipe.models.user_directory_path),
        ),
    ]
