# Generated by Django 4.2.14 on 2024-07-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_recipe', '0003_recipe_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(),
        ),
    ]
