# Generated by Django 4.2.14 on 2024-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_recipe', '0004_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
