name: Build, Test and Deploy Recipe Rabbit backend

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.TEST_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        docker compose up -d --build
        docker compose logs
    - name: Monitor resource usage
      run: |
        docker stats --no-stream &
        docker compose exec -T api pytest
        kill $!
